name:                tiger-haskell
version:             0.1.0.0
github:              "ry3s/tiger-haskell"
license:             BSD3
author:              "ry3s"
maintainer:          "example@example.com"
copyright:           "2019 ry3s"

extra-source-files:
- README.md
- ChangeLog.md
#- src/Lexer.x
# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ry3s/tiger-haskell#readme>

dependencies:
- base >= 4.7 && < 5


library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  dependencies:
    - array


executables:
  tiger:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tiger-haskell


tests:
  tiger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tiger-haskell
    - HUnit
